# Generated by Django 3.0.2 on 2020-02-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=20, null=True)),
                ('susnum', models.CharField(blank=True, db_column='susNum', max_length=20, null=True)),
                ('deathnum', models.CharField(blank=True, db_column='deathNum', max_length=20, null=True)),
                ('curenum', models.CharField(blank=True, db_column='cureNum', max_length=20, null=True)),
                ('city', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'virus',
            },
        ),
    ]
