# Generated by Django 3.0.3 on 2020-03-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('fileName', models.CharField(max_length=60)),
                ('alia', models.CharField(max_length=200)),
                ('path', models.FilePathField()),
            ],
        ),
    ]
